export const promoText = `_This post was generated by [Slack Archivist](https://github.com/jwulf/slack-archivist) from a conversation in the Zeebe Slack, a source of valuable discussions on Zeebe ([get an invite](https://zeebe-slack-invite.herokuapp.com/)). Someone in the Slack thought this was worth sharing!_
  
_If this post answered a question for you, hit the Like button - we use that to assess which posts to put into docs._`;
