export const promoText = `_This post was generated by [Slack Archivist](https://github.com/Camunda-DevRel/slack-archivist) from a conversation in the Camunda Platform 8 Slack, a source of valuable discussions on Camunda 8 ([join here](http://www.camunda.com/slack)). Someone in the Slack thought this was worth sharing!_
  
_If this post answered a question for you, hit the Like button - we use that to assess which posts to put into docs._`;
