import { Configuration } from "../src/lib/Configuration";

const configJSON = {
  slack: {
    token: "shntnshtnhs",
    signingSecret: "shntshntshn",
    promoMessage:
      "This post was generated by [Slack Archivist](https://github.com/jwulf/slack-archivist) from a conversation in the Zeebe Slack, a source of valuable discussions on Zeebe ([get an invite](https://zeebe-slack-invite.herokuapp.com/)). Someone in the Slack thought this was worth sharing!",
  },
  discourse: {
    token: "shnthnstnhs",
    user: "shntsnhtnhs",
    url: "https://forum.zeebe.io/",
    category: 16,
  },
};
describe("configuration", () => {
  it("exists", () => {
    expect(Configuration).toBeTruthy();
  });
  it("detects missing config", async () => {
    const config = new Configuration().validate();
    expect(config.isValid).toBe(false);
    expect(config.missingRequiredKeys.slack).toBeTruthy();
    expect(config.missingRequiredKeys.discourse).toBeTruthy();
    expect(Object.keys(config.missingRequiredKeys).length).toBe(2);
  });
  it("works with provided config", () => {
    const config = new Configuration(configJSON).validate();
    expect(config.isValid).toBe(true);
  });
});
